services:
  migration:
    image: tutorials-api:production
    command: prisma migrate deploy
  api:
    image: tutorials-api:production
    restart: always
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - 3000:3000
  cron:
    image: tutorials-api:production
    command: aomex cron:start
    restart: always
